# Generated by Django 5.1.4 on 2025-01-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.CharField(default="", max_length=250),
        ),
    ]
